version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-07-16T23-46-41Z
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  app:
    build: .
    depends_on:
      - minio
      - postgres
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - UNIPDF_LICENSE_KEY=7a997b47a356b861c27b727a1093104e55eace9eb185ccab3c8a463c3e1bb842
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13.4
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data:
